parameters:
    ez_recommendation.api_endpoint: 'https://admin.yoochoose.net'
    ez_recommendation.recommender.api_endpoint: 'http://event.yoochoose.net'
    ez_recommendation.recommender.consume_timeout: 20
    ez_recommendation.tracking.api_endpoint: 'http://event.yoochoose.net'
    ez_recommendation.tracking.script_url: 'cdn.yoochoose.net/yct.js'
