parameters:
    ez_recommendation.client.yoochoose_notifier.class: EzSystems\RecommendationBundle\Client\YooChooseNotifier

services:
    ez_recommendation.client.yoochoose_notifier:
        class: %ez_recommendation.client.yoochoose_notifier.class%
        arguments:
            - @ez_recommendation.client.yoochoose_notifier.guzzle_client
            - {api-endpoint: %ez_recommendation.api_endpoint%}
            - @?logger
        calls:
            - [setCustomerId, [$yoochoose.customer_id;ez_recommendation$]]
            - [setLicenseKey, [$yoochoose.license_key;ez_recommendation$]]
            - [setServerUri, [$server_uri;ez_recommendation$]]
        tags:
            - { name: monolog.logger, channel: ez_recommendation }

    ez_recommendation.client.yoochoose_notifier.guzzle_client:
        class: GuzzleHttp\Client
        arguments:
            - { base_url: %ez_recommendation.api_endpoint% }

    ez_recommendation.twig.tracker_extension:
        alias: ez_recommendation.twig.tracker_extension.yoochose

    ez_recommendation.twig.tracker_extension.yoochose:
        class: EzSystems\RecommendationBundle\Twig\YooChooseTrackerExtension
        arguments: [%ez_recommendation.yoochoose_tracker_template%]
        calls:
            - [setCustomerId, [$yoochoose.customer_id;ez_recommendation$]]
        tags:
            - { name: twig.extension }
