parameters:
    ez_recommendation.client.yoochoose_notifier.class: EzSystems\RecommendationBundle\Client\YooChooseNotifier
    ez_recommendation.twig.extension.class: EzSystems\RecommendationBundle\Twig\RecommendationTwigExtension
    ez_recommendation.event_listener.login.class: EzSystems\RecommendationBundle\EventListener\Login
    ez_recommendation.event_listener.session_backup.class: EzSystems\RecommendationBundle\EventListener\SessionBackup

services:
    ez_recommendation.client.yoochoose_notifier:
        class: %ez_recommendation.client.yoochoose_notifier.class%
        arguments:
            - @ez_recommendation.client.yoochoose_notifier.guzzle_client
            - @ezpublish.api.service.content
            - @ezpublish.api.service.content_type
            - {api-endpoint: %ez_recommendation.api_endpoint%}
            - @?logger
        calls:
            - [setCustomerId, [$yoochoose.customer_id;ez_recommendation$]]
            - [setLicenseKey, [$yoochoose.license_key;ez_recommendation$]]
            - [setServerUri, [$server_uri;ez_recommendation$]]
            - [setIncludedContentTypes, [$recommender.included_content_types;ez_recommendation$]]
        tags:
            - { name: monolog.logger, channel: ez_recommendation }

    ez_recommendation.client.yoochoose_notifier.guzzle_client:
        class: GuzzleHttp\Client
        arguments:
            - { base_url: %ez_recommendation.api_endpoint% }

    # The configured eZ Publish legacy search engine
    ez_recommendation.legacy.search_engine:
        class: ezpSearchEngine
        factory_class: EzSystems\RecommendationBundle\eZ\Publish\LegacySearch\LegacySearchFactory
        factory_method: build
        arguments: [@ezpublish_legacy.kernel]

    ez_recommendation.legacy.recommendation_search_engine:
        class: EzSystems\RecommendationBundle\eZ\Publish\LegacySearch\RecommendationLegacySearchEngine
        arguments:
            - @ez_recommendation.client.yoochoose_notifier
            - @ez_recommendation.legacy.search_engine

    ez_recommendation.legacy.search_configuration_mapper:
        class: EzSystems\RecommendationBundle\eZ\Publish\LegacySearch\ConfigurationMapper
        arguments:
            - @ez_recommendation.legacy.recommendation_search_engine
            - @ezpublish.siteaccess
        tags:
            - { name: kernel.event_subscriber }

    ez_recommendation.twig.extension:
        class: %ez_recommendation.twig.extension.class%
        public: true
        arguments:
            - @request_stack
            - @ezpublish.api.repository
            - @ezpublish.api.service.content_type
            - @ezpublish.api.service.content
            - @ezpublish.api.service.location
            - @ezpublish.locale.converter
            - @security.authorization_checker
            - @session
            - recommenderEndPoint: %ez_recommendation.recommender.api_endpoint%
              consumeTimeout: %ez_recommendation.recommender.consume_timeout%
              trackingScriptUrl: %ez_recommendation.tracking.script_url%
              trackingEndPoint: %ez_recommendation.tracking.api_endpoint%
        calls:
            - [setIncludedContentTypes, [$recommender.included_content_types;ez_recommendation$]]
            - [setCustomerId, [$yoochoose.customer_id;ez_recommendation$]]
        tags:
            - { name: twig.extension }

    ez_recommendation.event_listener.login:
        class: %ez_recommendation.event_listener.login.class%
        arguments:
            - @security.authorization_checker
            - @session
            - @ez_recommendation.client.yoochoose_notifier.guzzle_client
            - trackingEndPoint: %ez_recommendation.tracking.api_endpoint%
            - @?logger
        calls:
            - [setCustomerId, [$yoochoose.customer_id;ez_recommendation$]]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: monolog.logger, channel: ez_recommendation }

    ez_recommendation.event_listener.session_backup:
        class: %ez_recommendation.event_listener.session_backup.class%
        arguments:
            - @session
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
